name: Download a copy of the German Bundestag Lobbyregister daily
on:
  schedule:
    - cron: '0 22 * * *'  # every day at midnight Berlin time
  workflow_dispatch:
jobs:
  download-copy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          sparse-checkout: |
            .github
            ./data/recent
      - run: wget --content-disposition https://www.lobbyregister.bundestag.de/sucheDetailJson?sort=REGISTRATION_DESC
        working-directory: ./data/recent
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
            disable_globbing: true
            commit_message: Daily Update Bundestag Lobbyregister Data
