name: Download a copy of the German Bundestag Lobbyregister daily

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  download-copy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      TZ: Europe/Berlin

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          sparse-checkout: |
            .github
            data/recent

      - name: Ensure folder exists
        run: mkdir -p data/recent

      - name: Download + compress JSON (streaming)
        run: |
          ts="$(date +%Y-%m-%d)"
          curl -L -sS \
            'https://www.lobbyregister.bundestag.de/sucheDetailJson?sort=REGISTRATION_DESC' \
            | gzip -9 > "data/recent/lobbyregister_${ts}.json.gz"
          # (optional) checksum for integrity
          sha256sum "data/recent/lobbyregister_${ts}.json.gz" | tee "data/recent/lobbyregister_${ts}.sha256"
          ls -lh data/recent

      - name: Commit compressed file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Daily Update: Bundestag Lobbyregister Data (gzipped)"
          add_options: '--all --force'
          file_pattern: |
            data/recent/*.json.gz
            data/recent/*.sha256
